#!/usr/bin/env bash
# Installs nginx 
# Listens on port 80
# Serves a page that returns Hello World

sudo apt update -y
sudo apt install -y nginx
sudo mkdir -p /var/www/html
sudo chown -R "$USER":"$USER" /var/www/html
sudo chown -R "$USER":"$USER" /etc/nginx

echo "Hello World!" > /var/www/html/index.html
echo "http {
	server {
	listen      80 default_server;
	listen      [::]:80 default_server;
	root        /var/www/html;
	index       index.html index.htm;
	location / {
	root    /var/www/html;
	}
	loction /redirect_me {
	return 301 http://google.com/;
	}
	}
	}
	events {}
" > /etc/nginx/nginx.conf
sudo nginx -t
sudo nginx -s reload
