#!/usr/bin/env bash
# Installs nginx 
# Listens on port 80
# Serves a page that returns Hello World

sudo apt update -y
sudo apt install -y nginx
sudo mkdir -p /var/www/html
sudo chown -R $USER:$USER /var/www/html
sudo chown -R $USER:$USER /etc/nginx

echo "Ceci n'est pas une page" > /var/www/html/404.html
echo "Hello World!" > /var/www/html/index.html
echo "http {
	server {
	listen      80 default_server;
	listen      [::]:80 default_server;
	root        /var/www/html;
	index       index.html index.htm;
	location / {
	root    /var/www/html;
	}
	location /redirect_me {
	return 301 http://google.com/;
	}
	error_page 404 /404.html;
	location /404 {
	root /var/www/html;
	internal;
	}
	}
	}
	events {}
" > /etc/nginx/nginx.conf
sudo nginx -t
sudo nginx -s reload
