#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
# Configure HAproxy so that it send traffic to web-01 and web-02
# Distribute requests using a roundrobin algorithm
# Make sure that HAproxy can be managed via an init script

#CFG="\\nlisten lb 0.0.0.0:80\n\tmode http\n\tbalance roundrobin\n\toption httpclose\n\toption forwardfor\n\tserver 132025-web-01 52.91.117.92 check\n\tserver 132025-web-02 100.25.111.11 check\n"
CFG="\\nfrontend lb_frontend\n\tbind *:80\n\tmode http\n\tdefault_backend lb_backend\nbackend lb_backend\n\tbalance roundrobin\n\tserver web-01 52.91.117.92:80 check\n\tserver web-02 100.25.111.11:80 check\n"


sudo apt-get update
sudo apt-get install -y haproxy

sudo sed -i "\$a\ $CFG" /etc/haproxy/haproxy.cfg

# echo "frontend www-http
#     bind *:80
#     default_backend www-backend

# backend www-backend
#     balance roundrobin
#     server web-01 52.91.117.92:80 check
#     server web-02 100.25.111.11:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy restart
