#!/usr/bin/env bash
# Displays Best School 10 times using while loop.
# but for the 9th iteration, display Best School
# then Hi on a new line.

i=1
while (( i <= 10 ))
do
	echo "Best School"
	if [[ i -eq 9 ]]; then
		echo "Hi"
	fi
	((i++))
done
