#!/usr/bin/env bash
#Displays "Best School" but
#on the 9th iteration displays "Hi"

i=0
msg="Best School"

while [ $i -le 9 ]
do
	echo "$msg"

	if [ $i == 8 ]
	then	
		echo "Hi"
	fi

	(( i++ ))
done
