#!/usr/bin/env bash
#Gives you the information
#about the school file

file="./school"

if [ -e "$file" ]
then
	echo "school file exists"
	if [ ! -s "$file" ]
	then
		echo "school file is empty"
	else
		echo "school file is not empty"
	fi
else
	echo "school file does not exist"
fi


if [ -f "$file" ]
then
	echo "school is a regular file"
fi
